### ISSUE TITLE
Not able to create the source connector

### ISSUE THREAD

**Issue by felipegutierrez** [felipegutierrez/kafka-connector-github-source#1]
when executing the command `connect-distributed config/worker.properties config/GithubSourceConnector.properties` I have the error:

```
[2021-04-28 14:07:39,066] ERROR [Worker clientId=connect-1, groupId=1] Uncaught exception in herder work thread, exiting:  (org.apache.kafka.connect.runtime.distributed.DistributedHerder:325)
org.apache.kafka.connect.errors.ConnectException: Unable to create topic(s) 'offsets-storage-topic': Unknown topic config name: file.filename
	at org.apache.kafka.connect.util.TopicAdmin.createOrFindTopics(TopicAdmin.java:418)
	at org.apache.kafka.connect.util.TopicAdmin.createTopics(TopicAdmin.java:332)
	at org.apache.kafka.connect.storage.KafkaOffsetBackingStore.lambda$createKafkaBasedLog$0(KafkaOffsetBackingStore.java:135)
	at org.apache.kafka.connect.util.KafkaBasedLog.start(KafkaBasedLog.java:166)
	at org.apache.kafka.connect.storage.KafkaOffsetBackingStore.start(KafkaOffsetBackingStore.java:149)
	at org.apache.kafka.connect.runtime.Worker.start(Worker.java:203)
	at org.apache.kafka.connect.runtime.AbstractHerder.startServices(AbstractHerder.java:128)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:311)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.kafka.common.errors.InvalidConfigurationException: Unknown topic config name: file.filename
```
This is the complete stacktrace:
```
[2021-04-28 14:07:39,056] WARN The configuration 'expose.internal.connect.endpoints' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
[2021-04-28 14:07:39,056] WARN The configuration 'config.storage.topic' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
[2021-04-28 14:07:39,056] WARN The configuration 'metrics.context.connect.group.id' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
[2021-04-28 14:07:39,056] WARN The configuration 'group.id' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
[2021-04-28 14:07:39,057] WARN The configuration 'status.storage.topic' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
[2021-04-28 14:07:39,057] WARN The configuration 'rest.host.name' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
[2021-04-28 14:07:39,057] WARN The configuration 'internal.key.converter.schemas.enable' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
[2021-04-28 14:07:39,057] WARN The configuration 'rest.port' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
[2021-04-28 14:07:39,057] WARN The configuration 'offset.flush.interval.ms' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
[2021-04-28 14:07:39,057] WARN The configuration 'key.converter.schemas.enable' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
[2021-04-28 14:07:39,057] WARN The configuration 'internal.key.converter' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
[2021-04-28 14:07:39,057] WARN The configuration 'offset.storage.file.filename' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
[2021-04-28 14:07:39,057] WARN The configuration 'metrics.context.connect.kafka.cluster.id' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
[2021-04-28 14:07:39,057] WARN The configuration 'internal.value.converter.schemas.enable' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
[2021-04-28 14:07:39,057] WARN The configuration 'internal.value.converter' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
[2021-04-28 14:07:39,057] WARN The configuration 'value.converter.schemas.enable' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
[2021-04-28 14:07:39,057] WARN The configuration 'offset.storage.topic' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
[2021-04-28 14:07:39,057] WARN The configuration 'value.converter' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
[2021-04-28 14:07:39,057] WARN The configuration 'key.converter' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
[2021-04-28 14:07:39,058] INFO Kafka version: 6.1.1-ce (org.apache.kafka.common.utils.AppInfoParser:119)
[2021-04-28 14:07:39,058] INFO Kafka commitId: bed3428d56b4e9cb (org.apache.kafka.common.utils.AppInfoParser:120)
[2021-04-28 14:07:39,058] INFO Kafka startTimeMs: 1619611659057 (org.apache.kafka.common.utils.AppInfoParser:121)
[2021-04-28 14:07:39,066] ERROR [Worker clientId=connect-1, groupId=1] Uncaught exception in herder work thread, exiting:  (org.apache.kafka.connect.runtime.distributed.DistributedHerder:325)
org.apache.kafka.connect.errors.ConnectException: Unable to create topic(s) 'offsets-storage-topic': Unknown topic config name: file.filename
	at org.apache.kafka.connect.util.TopicAdmin.createOrFindTopics(TopicAdmin.java:418)
	at org.apache.kafka.connect.util.TopicAdmin.createTopics(TopicAdmin.java:332)
	at org.apache.kafka.connect.storage.KafkaOffsetBackingStore.lambda$createKafkaBasedLog$0(KafkaOffsetBackingStore.java:135)
	at org.apache.kafka.connect.util.KafkaBasedLog.start(KafkaBasedLog.java:166)
	at org.apache.kafka.connect.storage.KafkaOffsetBackingStore.start(KafkaOffsetBackingStore.java:149)
	at org.apache.kafka.connect.runtime.Worker.start(Worker.java:203)
	at org.apache.kafka.connect.runtime.AbstractHerder.startServices(AbstractHerder.java:128)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:311)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.kafka.common.errors.InvalidConfigurationException: Unknown topic config name: file.filename
[2021-04-28 14:07:39,071] INFO Stopped http_127.0.0.18086@2bec068b{HTTP/1.1, (http/1.1)}{127.0.0.1:8086} (org.eclipse.jetty.server.AbstractConnector:381)
[2021-04-28 14:07:39,085] INFO Adding admin resources to main listener (org.apache.kafka.connect.runtime.rest.RestServer:244)
[2021-04-28 14:07:39,129] INFO DefaultSessionIdManager workerName=node0 (org.eclipse.jetty.server.session:334)
[2021-04-28 14:07:39,129] INFO No SessionScavenger set, using defaults (org.eclipse.jetty.server.session:339)
[2021-04-28 14:07:39,130] INFO node0 Scavenging every 600000ms (org.eclipse.jetty.server.session:132)
[2021-04-28 14:07:39,419] INFO HV000001: Hibernate Validator 6.1.7.Final (org.hibernate.validator.internal.util.Version:21)



[2021-04-28 14:07:39,555] INFO Started o.e.j.s.ServletContextHandler@3e2d44f3{/,null,AVAILABLE} (org.eclipse.jetty.server.handler.ContextHandler:916)
[2021-04-28 14:07:39,555] INFO REST resources initialized; server is started and ready to handle requests (org.apache.kafka.connect.runtime.rest.RestServer:324)
[2021-04-28 14:07:39,555] INFO Kafka Connect started (org.apache.kafka.connect.runtime.Connect:57)
[2021-04-28 14:07:39,555] INFO Kafka Connect stopping (org.apache.kafka.connect.runtime.Connect:67)
[2021-04-28 14:07:39,556] INFO Stopping REST server (org.apache.kafka.connect.runtime.rest.RestServer:332)
[2021-04-28 14:07:39,556] INFO REST server stopped (org.apache.kafka.connect.runtime.rest.RestServer:349)
[2021-04-28 14:07:39,556] INFO [Worker clientId=connect-1, groupId=1] Herder stopping (org.apache.kafka.connect.runtime.distributed.DistributedHerder:713)

[2021-04-28 14:07:44,556] INFO [Worker clientId=connect-1, groupId=1] Herder stopped (org.apache.kafka.connect.runtime.distributed.DistributedHerder:733)
[2021-04-28 14:07:44,557] INFO Kafka Connect stopped (org.apache.kafka.connect.runtime.Connect:72)
```

**Comment by felipegutierrez** [comment]
fixed using default topics at `worker.properties` : `connect-distributed config/worker.properties config/GithubSourceConnector.properties`

```
offset.storage.topic=connect-offsets
config.storage.topic=connect-configs
status.storage.topic=connect-status
```
