### ISSUE TITLE
Error parsing JSON from github issues

### ISSUE THREAD

**Issue by felipegutierrez** [felipegutierrez/kafka-connector-github-source#2]
Error when executed `connect-distributed config/worker.properties config/GithubSourceConnector.properties`

```
[2021-04-28 18:29:55,118] ERROR Failed to convert config data to Kafka Connect format:  (org.apache.kafka.connect.storage.KafkaConfigBackingStore:546)
org.apache.kafka.connect.errors.DataException: JsonConverter with schemas.enable requires "schema" and "payload" fields and may not contain additional fields. If you are trying to deserialize plain JSON data, set schemas.enable=false in your converter configuration.
	at org.apache.kafka.connect.json.JsonConverter.toConnectData(JsonConverter.java:370)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore$ConsumeCallback.onCompletion(KafkaConfigBackingStore.java:544)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore$ConsumeCallback.onCompletion(KafkaConfigBackingStore.java:533)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:321)
	at org.apache.kafka.connect.util.KafkaBasedLog.readToLogEnd(KafkaBasedLog.java:348)
	at org.apache.kafka.connect.util.KafkaBasedLog.start(KafkaBasedLog.java:197)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore.start(KafkaConfigBackingStore.java:278)
	at org.apache.kafka.connect.runtime.AbstractHerder.startServices(AbstractHerder.java:130)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:311)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
and ...
```
[2021-04-28 14:20:09,789] ERROR Failed to convert config data to Kafka Connect format:  (org.apache.kafka.connect.storage.KafkaConfigBackingStore:546)
org.apache.kafka.connect.errors.DataException: JsonConverter with schemas.enable requires "schema" and "payload" fields and may not contain additional fields. If you are trying to deserialize plain JSON data, set schemas.enable=false in your converter configuration.
	at org.apache.kafka.connect.json.JsonConverter.toConnectData(JsonConverter.java:370)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore$ConsumeCallback.onCompletion(KafkaConfigBackingStore.java:544)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore$ConsumeCallback.onCompletion(KafkaConfigBackingStore.java:533)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:321)
	at org.apache.kafka.connect.util.KafkaBasedLog.readToLogEnd(KafkaBasedLog.java:348)
	at org.apache.kafka.connect.util.KafkaBasedLog.start(KafkaBasedLog.java:197)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore.start(KafkaConfigBackingStore.java:278)
	at org.apache.kafka.connect.runtime.AbstractHerder.startServices(AbstractHerder.java:130)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:311)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
[2021-04-28 14:20:09,790] ERROR Failed to convert config data to Kafka Connect format:  (org.apache.kafka.connect.storage.KafkaConfigBackingStore:546)
org.apache.kafka.connect.errors.DataException: JsonConverter with schemas.enable requires "schema" and "payload" fields and may not contain additional fields. If you are trying to deserialize plain JSON data, set schemas.enable=false in your converter configuration.
	at org.apache.kafka.connect.json.JsonConverter.toConnectData(JsonConverter.java:370)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore$ConsumeCallback.onCompletion(KafkaConfigBackingStore.java:544)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore$ConsumeCallback.onCompletion(KafkaConfigBackingStore.java:533)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:321)
	at org.apache.kafka.connect.util.KafkaBasedLog.readToLogEnd(KafkaBasedLog.java:348)
	at org.apache.kafka.connect.util.KafkaBasedLog.start(KafkaBasedLog.java:197)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore.start(KafkaConfigBackingStore.java:278)
	at org.apache.kafka.connect.runtime.AbstractHerder.startServices(AbstractHerder.java:130)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:311)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
[2021-04-28 14:20:09,790] ERROR Failed to convert config data to Kafka Connect format:  (org.apache.kafka.connect.storage.KafkaConfigBackingStore:546)
org.apache.kafka.connect.errors.DataException: JsonConverter with schemas.enable requires "schema" and "payload" fields and may not contain additional fields. If you are trying to deserialize plain JSON data, set schemas.enable=false in your converter configuration.
	at org.apache.kafka.connect.json.JsonConverter.toConnectData(JsonConverter.java:370)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore$ConsumeCallback.onCompletion(KafkaConfigBackingStore.java:544)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore$ConsumeCallback.onCompletion(KafkaConfigBackingStore.java:533)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:321)
	at org.apache.kafka.connect.util.KafkaBasedLog.readToLogEnd(KafkaBasedLog.java:348)
	at org.apache.kafka.connect.util.KafkaBasedLog.start(KafkaBasedLog.java:197)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore.start(KafkaConfigBackingStore.java:278)
	at org.apache.kafka.connect.runtime.AbstractHerder.startServices(AbstractHerder.java:130)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:311)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
[2021-04-28 14:20:09,791] ERROR Failed to convert config data to Kafka Connect format:  (org.apache.kafka.connect.storage.KafkaConfigBackingStore:546)
org.apache.kafka.connect.errors.DataException: JsonConverter with schemas.enable requires "schema" and "payload" fields and may not contain additional fields. If you are trying to deserialize plain JSON data, set schemas.enable=false in your converter configuration.
	at org.apache.kafka.connect.json.JsonConverter.toConnectData(JsonConverter.java:370)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore$ConsumeCallback.onCompletion(KafkaConfigBackingStore.java:544)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore$ConsumeCallback.onCompletion(KafkaConfigBackingStore.java:533)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:321)
	at org.apache.kafka.connect.util.KafkaBasedLog.readToLogEnd(KafkaBasedLog.java:348)
	at org.apache.kafka.connect.util.KafkaBasedLog.start(KafkaBasedLog.java:197)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore.start(KafkaConfigBackingStore.java:278)
	at org.apache.kafka.connect.runtime.AbstractHerder.startServices(AbstractHerder.java:130)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:311)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
[2021-04-28 14:20:09,791] ERROR Failed to convert config data to Kafka Connect format:  (org.apache.kafka.connect.storage.KafkaConfigBackingStore:546)
org.apache.kafka.connect.errors.DataException: JsonConverter with schemas.enable requires "schema" and "payload" fields and may not contain additional fields. If you are trying to deserialize plain JSON data, set schemas.enable=false in your converter configuration.
	at org.apache.kafka.connect.json.JsonConverter.toConnectData(JsonConverter.java:370)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore$ConsumeCallback.onCompletion(KafkaConfigBackingStore.java:544)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore$ConsumeCallback.onCompletion(KafkaConfigBackingStore.java:533)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:321)
	at org.apache.kafka.connect.util.KafkaBasedLog.readToLogEnd(KafkaBasedLog.java:348)
	at org.apache.kafka.connect.util.KafkaBasedLog.start(KafkaBasedLog.java:197)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore.start(KafkaConfigBackingStore.java:278)
	at org.apache.kafka.connect.runtime.AbstractHerder.startServices(AbstractHerder.java:130)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:311)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
[2021-04-28 14:20:09,791] ERROR Failed to convert config data to Kafka Connect format:  (org.apache.kafka.connect.storage.KafkaConfigBackingStore:546)
org.apache.kafka.connect.errors.DataException: JsonConverter with schemas.enable requires "schema" and "payload" fields and may not contain additional fields. If you are trying to deserialize plain JSON data, set schemas.enable=false in your converter configuration.
	at org.apache.kafka.connect.json.JsonConverter.toConnectData(JsonConverter.java:370)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore$ConsumeCallback.onCompletion(KafkaConfigBackingStore.java:544)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore$ConsumeCallback.onCompletion(KafkaConfigBackingStore.java:533)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:321)
	at org.apache.kafka.connect.util.KafkaBasedLog.readToLogEnd(KafkaBasedLog.java:348)
	at org.apache.kafka.connect.util.KafkaBasedLog.start(KafkaBasedLog.java:197)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore.start(KafkaConfigBackingStore.java:278)
	at org.apache.kafka.connect.runtime.AbstractHerder.startServices(AbstractHerder.java:130)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:311)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
[2021-04-28 14:20:09,791] ERROR Failed to convert config data to Kafka Connect format:  (org.apache.kafka.connect.storage.KafkaConfigBackingStore:546)
org.apache.kafka.connect.errors.DataException: JsonConverter with schemas.enable requires "schema" and "payload" fields and may not contain additional fields. If you are trying to deserialize plain JSON data, set schemas.enable=false in your converter configuration.
	at org.apache.kafka.connect.json.JsonConverter.toConnectData(JsonConverter.java:370)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore$ConsumeCallback.onCompletion(KafkaConfigBackingStore.java:544)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore$ConsumeCallback.onCompletion(KafkaConfigBackingStore.java:533)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:321)
	at org.apache.kafka.connect.util.KafkaBasedLog.readToLogEnd(KafkaBasedLog.java:348)
	at org.apache.kafka.connect.util.KafkaBasedLog.start(KafkaBasedLog.java:197)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore.start(KafkaConfigBackingStore.java:278)
	at org.apache.kafka.connect.runtime.AbstractHerder.startServices(AbstractHerder.java:130)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:311)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
[2021-04-28 14:20:09,792] ERROR Failed to convert config data to Kafka Connect format:  (org.apache.kafka.connect.storage.KafkaConfigBackingStore:546)
org.apache.kafka.connect.errors.DataException: JsonConverter with schemas.enable requires "schema" and "payload" fields and may not contain additional fields. If you are trying to deserialize plain JSON data, set schemas.enable=false in your converter configuration.
	at org.apache.kafka.connect.json.JsonConverter.toConnectData(JsonConverter.java:370)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore$ConsumeCallback.onCompletion(KafkaConfigBackingStore.java:544)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore$ConsumeCallback.onCompletion(KafkaConfigBackingStore.java:533)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:321)
	at org.apache.kafka.connect.util.KafkaBasedLog.readToLogEnd(KafkaBasedLog.java:348)
	at org.apache.kafka.connect.util.KafkaBasedLog.start(KafkaBasedLog.java:197)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore.start(KafkaConfigBackingStore.java:278)
	at org.apache.kafka.connect.runtime.AbstractHerder.startServices(AbstractHerder.java:130)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:311)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
[2021-04-28 14:20:09,792] ERROR Failed to convert config data to Kafka Connect format:  (org.apache.kafka.connect.storage.KafkaConfigBackingStore:546)
org.apache.kafka.connect.errors.DataException: JsonConverter with schemas.enable requires "schema" and "payload" fields and may not contain additional fields. If you are trying to deserialize plain JSON data, set schemas.enable=false in your converter configuration.
	at org.apache.kafka.connect.json.JsonConverter.toConnectData(JsonConverter.java:370)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore$ConsumeCallback.onCompletion(KafkaConfigBackingStore.java:544)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore$ConsumeCallback.onCompletion(KafkaConfigBackingStore.java:533)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:321)
	at org.apache.kafka.connect.util.KafkaBasedLog.readToLogEnd(KafkaBasedLog.java:348)
	at org.apache.kafka.connect.util.KafkaBasedLog.start(KafkaBasedLog.java:197)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore.start(KafkaConfigBackingStore.java:278)
	at org.apache.kafka.connect.runtime.AbstractHerder.startServices(AbstractHerder.java:130)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:311)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
[2021-04-28 14:20:09,792] ERROR Failed to convert config data to Kafka Connect format:  (org.apache.kafka.connect.storage.KafkaConfigBackingStore:546)
org.apache.kafka.connect.errors.DataException: JsonConverter with schemas.enable requires "schema" and "payload" fields and may not contain additional fields. If you are trying to deserialize plain JSON data, set schemas.enable=false in your converter configuration.
	at org.apache.kafka.connect.json.JsonConverter.toConnectData(JsonConverter.java:370)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore$ConsumeCallback.onCompletion(KafkaConfigBackingStore.java:544)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore$ConsumeCallback.onCompletion(KafkaConfigBackingStore.java:533)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:321)
	at org.apache.kafka.connect.util.KafkaBasedLog.readToLogEnd(KafkaBasedLog.java:348)
	at org.apache.kafka.connect.util.KafkaBasedLog.start(KafkaBasedLog.java:197)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore.start(KafkaConfigBackingStore.java:278)
	at org.apache.kafka.connect.runtime.AbstractHerder.startServices(AbstractHerder.java:130)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:311)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
[2021-04-28 14:20:09,792] ERROR Failed to convert config data to Kafka Connect format:  (org.apache.kafka.connect.storage.KafkaConfigBackingStore:546)
org.apache.kafka.connect.errors.DataException: JsonConverter with schemas.enable requires "schema" and "payload" fields and may not contain additional fields. If you are trying to deserialize plain JSON data, set schemas.enable=false in your converter configuration.
	at org.apache.kafka.connect.json.JsonConverter.toConnectData(JsonConverter.java:370)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore$ConsumeCallback.onCompletion(KafkaConfigBackingStore.java:544)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore$ConsumeCallback.onCompletion(KafkaConfigBackingStore.java:533)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:321)
	at org.apache.kafka.connect.util.KafkaBasedLog.readToLogEnd(KafkaBasedLog.java:348)
	at org.apache.kafka.connect.util.KafkaBasedLog.start(KafkaBasedLog.java:197)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore.start(KafkaConfigBackingStore.java:278)
	at org.apache.kafka.connect.runtime.AbstractHerder.startServices(AbstractHerder.java:130)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:311)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
[2021-04-28 14:20:09,793] INFO Finished reading KafkaBasedLog for topic connect-configs (org.apache.kafka.connect.util.KafkaBasedLog:202)

```

**Comment by felipegutierrez** [comment]
Fixed using the following configuration to create the connector:
```
{
  "name": "GitHubSourceConnectorConnectorDemo",
  "connector.class": "com.github.felipegutierrez.kafka.connector.github.GitHubSourceConnector",
  "tasks.max": "1",
  "key.converter": "org.apache.kafka.connect.json.JsonConverter",
  "value.converter": "org.apache.kafka.connect.json.JsonConverter",
  "topic": "github-issues",
  "github.owner": "kubernetes",
  "github.repo": "kubernetes",
  "batch.size": "2",
  "since.timestamp": "2021-01-01T00:00:00Z",
  "auth.username": "USERNAME",
  "auth.password": "PASSWORD"
}
```
and 
```
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false
```
